# Generated by Django 4.1.5 on 2023-02-01 07:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicule_flotte',
            fields=[
                ('vehicule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parc.vehicule')),
                ('disponible', models.BooleanField(default=True)),
            ],
            bases=('parc.vehicule',),
        ),
        migrations.CreateModel(
            name='Flotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField(default=datetime.date.today)),
                ('fin', models.DateField(default=datetime.date.today)),
                ('charge', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('statut', models.IntegerField(choices=[(0, 'Impayée'), (1, 'A réaliser'), (2, 'Annulée'), (3, 'Réalisée')], default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailFlotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Electric'), (1, 'Hybrid'), (2, 'Shared'), (3, 'Vélo'), (4, 'Trottinette')])),
                ('quantite', models.IntegerField()),
                ('flotte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flottes.flotte')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationFlotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flotte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flottes.flotte')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flottes.vehicule_flotte')),
            ],
        ),
    ]
