# Generated by Django 4.1.5 on 2023-02-01 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flottes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailflotte',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
