# Generated by Django 4.1.5 on 2023-02-03 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flottes', '0002_alter_detailflotte_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailflotte',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='flotte',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
