# Generated by Django 4.1.5 on 2023-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flottes', '0003_alter_detailflotte_quantite_alter_flotte_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailflotte',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
