# Generated by Django 4.1.5 on 2023-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flottes', '0004_detailflotte_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotte',
            name='mode_paiement',
            field=models.IntegerField(choices=[(0, 'Carte bancaire'), (1, 'Virement')], default=0),
        ),
    ]
