# Generated by Django 4.1.5 on 2023-01-26 05:18

from django.db import migrations, models
import django.db.models.deletion
import parc.model.model_parc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('marque', models.CharField(max_length=20)),
                ('modele', models.CharField(max_length=20)),
                ('nb_place', models.IntegerField(default=1)),
                ('type', models.IntegerField(choices=[(0, 'Electric'), (1, 'Hybrid'), (2, 'Diesel'), (3, 'Non motorized')], default=0)),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=parc.model.model_parc.path_photo_user)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actors.chauffeur')),
            ],
        ),
    ]
