# Generated by Django 4.1.5 on 2023-01-26 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0002_delete_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.reservation')),
                ('date', models.DateField(default=datetime.date.today)),
                ('depart', models.TimeField(blank=True, null=True)),
                ('statut', models.IntegerField(choices=[(0, 'Impayée'), (1, 'A réaliser'), (2, 'Annulée'), (3, 'Réalisée')], default=0)),
                ('aller_retour', models.BooleanField(default=False)),
                ('colis_1', models.BooleanField(default=False)),
                ('weight_1', models.IntegerField(default=0)),
                ('colis_2', models.BooleanField(default=False)),
                ('weight_2', models.IntegerField(default=0)),
                ('colis_3', models.BooleanField(default=False)),
                ('weight_3', models.IntegerField(default=0)),
                ('colis_4', models.BooleanField(default=False)),
                ('weight_4', models.IntegerField(default=0)),
                ('voiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservation.voiture_demande')),
            ],
            bases=('reservation.reservation',),
        ),
    ]
