# Generated by Django 4.1.5 on 2023-01-27 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='weight_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='weight_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='weight_3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='weight_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
    ]
