# Generated by Django 4.1.5 on 2023-01-27 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0002_alter_livraison_weight_1_alter_livraison_weight_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='weight_1',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(25.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='weight_2',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(25.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='weight_3',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(25.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='weight_4',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(25.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
