# Generated by Django 4.1.5 on 2023-01-26 05:16

import actors.model.actor
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.IntegerField(null=True, unique=True)),
                ('sexe', models.IntegerField(choices=[(0, 'Femme'), (1, 'Homme')], default=1)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=actors.model.actor.path_photo_user)),
                ('date_embauche', models.DateField(default=datetime.date.today, verbose_name="date d'embauche")),
                ('date_demission', models.DateField(null=True, verbose_name='date demission')),
                ('motif', models.IntegerField(choices=[(0, 'Démission'), (1, 'Licenciement'), (2, 'Retraite'), (3, 'Décès'), (4, 'Fin de contrat'), (5, 'Autre')], null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero', models.IntegerField(null=True, unique=True)),
                ('sexe', models.IntegerField(choices=[(0, 'Femme'), (1, 'Homme')], default=1)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=actors.model.actor.path_photo_user)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
