# Generated by Django 4.1.5 on 2023-01-26 05:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parc', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('depart', models.TimeField(blank=True, null=True)),
                ('arrivee', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne_reguliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='End_address', to='reservation.address')),
                ('adresse_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Start_address', to='reservation.address')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.TextField()),
                ('adresse_arrivee', models.TextField()),
                ('charge', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField()),
                ('nb_passager', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_cost', models.FloatField(default=15.0)),
                ('hybrid_coef', models.FloatField(default=1.0)),
                ('electric_coef', models.FloatField(default=1.05)),
            ],
        ),
        migrations.CreateModel(
            name='voiture_demande',
            fields=[
                ('vehicule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parc.vehicule')),
                ('disponible', models.BooleanField(default=True)),
            ],
            bases=('parc.vehicule',),
        ),
        migrations.CreateModel(
            name='voiture_reguliere',
            fields=[
                ('vehicule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parc.vehicule')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.ligne_reguliere')),
            ],
            bases=('parc.vehicule',),
        ),
        migrations.CreateModel(
            name='Reservation_Demande',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.reservation')),
                ('date', models.DateField(default=datetime.date.today)),
                ('depart', models.TimeField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Electric'), (1, 'Hybrid'), (2, 'Shared')])),
                ('statut', models.IntegerField(choices=[(0, 'Impayée'), (1, 'A réaliser'), (2, 'Annulée'), (3, 'Réalisée')], default=0)),
                ('aller_retour', models.BooleanField(default=False)),
                ('voiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservation.voiture_demande')),
            ],
            bases=('reservation.reservation',),
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.reservation')),
                ('date', models.DateField(default=datetime.date.today)),
                ('depart', models.TimeField(blank=True, null=True)),
                ('statut', models.IntegerField(choices=[(0, 'Impayée'), (1, 'A réaliser'), (2, 'Annulée'), (3, 'Réalisée')], default=0)),
                ('aller_retour', models.BooleanField(default=False)),
                ('colis_1', models.BooleanField(default=False)),
                ('weight_1', models.IntegerField(default=0)),
                ('colis_2', models.BooleanField(default=False)),
                ('weight_2', models.IntegerField(default=0)),
                ('colis_3', models.BooleanField(default=False)),
                ('weight_3', models.IntegerField(default=0)),
                ('colis_4', models.BooleanField(default=False)),
                ('weight_4', models.IntegerField(default=0)),
                ('voiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservation.voiture_demande')),
            ],
            bases=('reservation.reservation',),
        ),
    ]
