# Generated by Django 4.1.5 on 2023-01-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
