# Generated by Django 4.1.5 on 2023-01-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_delete_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='depot_cost',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='tarif',
            name='livraison_coef',
            field=models.FloatField(default=1.0),
        ),
    ]
