# Generated by Django 4.1.5 on 2023-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_tarif_depot_cost_tarif_livraison_coef'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='daily_cost',
            field=models.FloatField(default=300.0),
        ),
    ]
