# Generated by Django 4.1.5 on 2023-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_tarif_daily_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='shared_coef',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='tarif',
            name='trottinette_coef',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='tarif',
            name='velo_coef',
            field=models.FloatField(default=0.1),
        ),
    ]
